name: recent activity
on:
  schedule: [{ cron: "*/30 * * * *" }]
  workflow_dispatch:
permissions: { contents: write }
jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "Update recent activity"
          MAX_LINES: 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
